prompt Dropping existing Tables...
drop table persons cascade constraints;
drop table phone_numbers cascade constraints;
drop table countries cascade constraints;
drop table addresses cascade constraints;
drop table employee_details cascade constraints;
drop table jobs cascade constraints;
drop table menu_types cascade constraints;
drop table menus cascade constraints;
drop table nested_categories cascade constraints;
drop table items cascade constraints;
drop table item_prices cascade constraints;
drop table selections cascade constraints;
drop table extra_items cascade constraints;
drop table items_eitems cascade constraints;
drop table w_menus_prices cascade constraints;
drop table selection_groups cascade constraints;
drop table items_selgs cascade constraints;
drop table selgs_sels cascade constraints;
drop table awaiting_table;

purge dba_recyclebin;

prompt Creating Tables...
prompt - Creating Clients and Employees Tables
create table persons (
	pers_id number generated by default on null as identity,
	last_name varchar2(50) not null,
    first_name varchar2(50) not null,
    middle_names varchar2(150),
    gender char default 'I',
    email varchar2(150) not null,
    ptype char default 'C' not null, 
    birthdate date,
    constraint pk_persons primary key (pers_id),
    constraint ck_persons_ptype check(UPPER(ptype) in ('E', 'C')),
    constraint ck_persons_gender check(UPPER(gender) in ('I','M','F')),
    constraint ck_persons_email check(REGEXP_LIKE (UPPER(email), '[A-Z0-9._%-]+@[A-Z0-9._%-]+\.[A-Z]{2,4}'))
);

create table jobs (
	job_id number generated by default on null as identity,
	job_title varchar2(50) not null,
	parent_job_id number,
	constraint pk_jobs primary key (job_id),
	constraint fk_jobs_prt_job_id foreign key (parent_job_id) references jobs(job_id)
);

create table employee_details (
	emp_id number not null,
	manager_id number,
	job_id number not null,
	social_sec_num varchar2(20) not null,
	warnings number default 0 not null,
	salary number(6,2) not null,
	constraint pk_employee_details primary key (emp_id),
	constraint fk_employee_details_person_id foreign key (emp_id) references persons(pers_id) on delete cascade,
	constraint fk_employee_details_manager foreign key (manager_id) references employee_details(emp_id),
	constraint fk_employee_details_job_id foreign key (job_id) references jobs(job_id)
);

create table phone_numbers (
	emp_id number not null,
	phone_number varchar2(50) not null,
	phone_type varchar2(50) default 'PRIVATE' not null,
	constraint pk_phone_numbers primary key (emp_id, phone_number),
	constraint fk_phone_numbers_employees foreign key (emp_id) references employee_details(emp_id),
	constraint ck_phone_numbers_phone_type check (UPPER(phone_type) in ('MOBILE', 'PRIVATE', 'WORK', 'LANDLINE'))
);

create table countries (
	country_id number,
	iso varchar2(2),
	name varchar2(100),
	nicename varchar2(150),
	iso3 varchar2(3),
	numcode number,
	phonecode number,
	constraint pk_countries primary key (country_id)
);

create table addresses (
	address_id number generated by default on null as identity,
	emp_id number not null,
	address_street varchar2(200) not null,
	address_number varchar2(30),
	address_zip varchar2(20),
	address_city varchar2(150) not null,
	address_region varchar2(150),
	country_id number not null,
	constraint pk_addresses primary key (address_id, emp_id),
	constraint fk_addresses_employees foreign key (emp_id) references employee_details(emp_id),
	constraint fK_addresses_country_id foreign key (country_id) references countries(country_id)
);

prompt - Creating Inventory
create table menu_types (
	mt_id number generated by default on null as identity,
	name varchar2(50) not null,
	json_tag varchar2(50) not null,
	weighted number(1) default 0,
	constraint pk_mtypes primary key (mt_id),
	constraint ck_mtypes_weighted check (weighted = 0 or weighted = 1)
);

create table menus (
	menu_id number generated by default on null as identity,
	mt_id number,
	name varchar2(50) not null,
	description varchar2(1000),
	constraint pk_menus primary key (menu_id),
	constraint fk_menus_mtypes foreign key (mt_id) references menu_types(mt_id)
);

create table nested_categories (
	cat_id number generated by default on null as identity,
	menu_id number,
	name varchar2(50) not null,
	description varchar2(1000),
	lft number default 0 not null,
	rgt number default 1 not null,
	weight number default 0 not null ,
	constraint pk_nc primary key (cat_id),
	constraint fk_nc_menu_id foreign key (menu_id) references menus(menu_id),
	constraint ck_nc_lft_lt_rgt check (lft < rgt),
	constraint ck_nc_wgt_pos check (weight >= 0)
);


create table items (
	item_id number generated by default on null as identity,
	cat_id number,
	name varchar2(50) not null,
	subtitle varchar2(200),
	description varchar2(1000),
	allergenes number(5) default 0 not null,
	constraint pk_items primary key (item_id),
	constraint fk_items_cat_id foreign key (cat_id) references nested_categories(cat_id) on delete set null,
	constraint ck_items_allergenes_pos check (allergenes >= 0),
	constraint ck_items_allergenes_maxVal check (allergenes <= 16383)
);

create table item_prices (
	item_id number not null,
	price number(6,2) not null,
	price_name varchar2(50),
	constraint pk_item_prices primary key (item_id, price),
	constraint fk_item_prices_items foreign key (item_id) references items(item_id) on delete cascade,
	constraint ck_item_prices_price_pos check (price >= 0)
);

create table selection_groups (
	selg_id number generated by default on null as identity,
	name varchar2(50) not null,
	constraint pk_selgs primary key (selg_id),
	constraint ck_selgs_name check (length(name) >= 3)
);

create table items_selgs (
	item_id number not null,
	selg_id number not null,
	constraint pk_iselgs primary key (item_id, selg_id),
	constraint fk_iselgs_item_id foreign key (item_id) references items(item_id) on delete cascade,
	constraint fk_iselgs_selg_id foreign key (selg_id) references selection_groups(selg_id) on delete cascade
);

create table selections (
	sel_id number generated by default on null as identity,
	name varchar2(50) not null,
	description varchar2(1000),
	constraint pk_selections primary key (sel_id),
	constraint ck_selections_name_len check (length(name) >= 3)
);

create table selgs_sels (
	selg_id number not null,
	sel_id number not null,
	constraint pk_sgs primary key (selg_id, sel_id),
	constraint fk_sgs_selgs foreign key (selg_id) references selection_groups(selg_id) on delete cascade,
	constraint fk_sgs_selections foreign key (sel_id) references selections(sel_id) on delete cascade
);

create table extra_items (
	exitem_id number generated by default on null as identity,
	name varchar2(50) not null,
	allergenes number(5) default 0 not null,
	price number(3,2)default 0 not null ,
	constraint pk_ei primary key (exitem_id),
	constraint ck_ei_nam check (length(name) >= 3),
	constraint ck_ei_allergenes_pos check (allergenes >= 0),
	constraint ck_ei_allergenes_maxVal check (allergenes <= 16383),
	constraint ck_ei_price check (price >= 0)
);

create table items_eitems (
	item_id number,
	exitem_id number,
	constraint pk_iei primary key (item_id, exitem_id),
	constraint fk_iei_item_id foreign key (item_id) references items(item_id) on delete cascade,
	constraint fk_iei_exitem_id foreign key (exitem_id) references extra_items(exitem_id)
);

create table w_menus_prices (
	menu_id number not null,
	weight number not null,
	item_id number not null,
	constraint pk_wmp primary key (menu_id, weight),
	constraint fk_wmp_menu_id foreign key (menu_id) references menus(menu_id) on delete cascade,
	constraint fk_wmp_item_id foreign key (item_id) references items(item_id) on delete cascade,
	constraint ck_wmp_weight_pos check (weight > 0)
);

create table awaiting_table (
	current_rowid ROWID,
	action varchar2(6),
	filename VARCHAR2(25),
	content clob,
	constraint pk_at primary key (current_rowid),
	constraint ck_at_json check (content is json)
);