prompt 'Filling Time Dims'
begin
	fill_dim_date('01.01.2010','31.12.2030');
end;
/
begin
	fill_dim_time;
end;
/

prompt 'ADDING DEFAULT VALUES'

--DEFAULT VALUES + HISTORY (TODO)
INSERT INTO "PROD_MENUS" (PROD_MENUS_ID, ORIGINAL_MENU_ID, MENU_NAME, ORIGINAL_MT_ID, MT_NAME) VALUES ('-404', '-1', 'Unknown Menu', '-1', 'No Menu Type Information Available');
INSERT INTO "PROD_MENUS" (PROD_MENUS_ID, ORIGINAL_MENU_ID, MENU_NAME, ORIGINAL_MT_ID, MT_NAME) VALUES ('-2', '-2', 'Weighted Menu', '-1', 'Check Weighted Menu');

INSERT INTO "PROD_MENUS_HISTORY" (PROD_MENUS_ID, MENU_NAME, MT_NAME) VALUES ('-404', 'Unknown Menu', 'No Menu Type Information Available');
INSERT INTO "PROD_MENUS_HISTORY" (PROD_MENUS_ID, MENU_NAME, MT_NAME) VALUES ('-2', 'Weighted Menu', 'Check Weighted Menu');

INSERT INTO "PROD_CATEGORIES" (PROD_CAT_ID, ORIGINAL_CAT_ID, NAME, LFT, RGT, PROD_MENUS_ID) VALUES ('-404', '-1', 'Unknown Category', '0', '0', '-404');
INSERT INTO "PROD_CATEGORIES" (PROD_CAT_ID, ORIGINAL_CAT_ID, NAME, LFT, RGT, PROD_MENUS_ID) VALUES ('-2', '-2', 'Weighted Menu', '0', '0', '-2');

INSERT INTO "PROD_CATEGORIES_HISTORY" (PROD_CAT_ID, NAME, LFT, RGT, PROD_MENUS_ID) VALUES ('-404', 'Unknown Category', '0', '0', '-404');
INSERT INTO "PROD_CATEGORIES_HISTORY" (PROD_CAT_ID, NAME, LFT, RGT, PROD_MENUS_ID) VALUES ('-2', 'Weighted Menu', '0', '0', '-2');

INSERT INTO "PROD_ITEMS" (PROD_ITEMS_ID, ORIGINAL_ITEM_ID, NAME, SUBTITLE, DESCRIPTION, PRICE, PRICE_NAME, ALLERGENES, PROD_CAT_ID, PROD_MENUS_ID) VALUES ('-404', '-1', 'Unknown Item', '','','0','','0','-404', '-404');

INSERT INTO "PROD_ITEMS_HISTORY" (PROD_ITEMS_ID, NAME, SUBTITLE, DESCRIPTION, PRICE, PRICE_NAME, ALLERGENES, PROD_CAT_ID, PROD_MENUS_ID) VALUES ('-404', 'No Product Information Available', '','','0','','0','-404', '-404');

INSERT INTO "DIM_SELECTIONS" (DIM_SELECTIONS_ID, ORIGINAL_SELG_ID, SELG_NAME, ORIGINAL_SEL_ID, SEL_NAME) VALUES ('-404', '-1', 'Unknown Selection Group', '-1', 'Unknown Selection');
INSERT INTO "DIM_SELECTIONS" (DIM_SELECTIONS_ID, ORIGINAL_SELG_ID, SELG_NAME, ORIGINAL_SEL_ID, SEL_NAME) VALUES ('-1', '-1', 'No Selection Group', '-1', 'No Selection');

INSERT INTO "DIM_EMPLOYEES" (DIM_EMPLOYEES_ID, ORIGINAL_EMP_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAMES, BIRTHDATE, ORIGINAL_JOB_ID, JOB_TITLE) VALUES ('-404', '-1', 'Unknown Employee', 'Unknown', '', TO_DATE('1991-05-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), '-1', 'Unknown');
INSERT INTO "DIM_EMPLOYEES" (DIM_EMPLOYEES_ID, ORIGINAL_EMP_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAMES, BIRTHDATE, ORIGINAL_JOB_ID, JOB_TITLE) VALUES ('-10', '-2', 'Tablet PC', 'Tablet PC', 'Tablet PC', TO_DATE('1991-05-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), '-1', 'Tablet PC');

INSERT INTO "DIM_EMPLOYEES_HISTORY" (DIM_EMPLOYEES_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAMES, JOB_TITLE) VALUES ('-404', 'Unknown Employee', 'Unknown', '', 'Unknown');
INSERT INTO "DIM_EMPLOYEES_HISTORY" (DIM_EMPLOYEES_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAMES, JOB_TITLE) VALUES ('-10', 'Tablet PC', 'Tablet PC', 'Tablet PC', 'Tablet PC');

INSERT INTO "DIM_SESSIONS" (DIM_SESSIONS_ID, SESSION_GUID, SESSION_START, SESSION_CLOSED, SESSION_STATUS) VALUES ('-404', '-1', TO_DATE('1991-05-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('1991-05-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'E');

INSERT INTO "PROD_CUSTOM_ITEMS" (PROD_CUSTOM_ITEMS_ID, ORIGINAL_ITEM_ID, NAME, PROD_CAT_ID, PROD_MENUS_ID) VALUES ('-404', '-1', 'Unknown Custom Item', '-404', '-404');
INSERT INTO "PROD_CUSTOM_ITEMS" (PROD_CUSTOM_ITEMS_ID, ORIGINAL_ITEM_ID, NAME, PROD_CAT_ID, PROD_MENUS_ID) VALUES ('-1', '-1', 'No Custom Item Selected', '-404', '-404');

INSERT INTO "DIM_EXTRA_ITEMS" (DIM_EXTRA_ITEMS_ID, ORIGINAL_EXITEM_ID, NAME, PRICE, ALLERGENES) VALUES ('-1', '-1', 'No Extra Item Selected', '0','0');
INSERT INTO "DIM_EXTRA_ITEMS" (DIM_EXTRA_ITEMS_ID, ORIGINAL_EXITEM_ID, NAME, PRICE, ALLERGENES) VALUES ('-404', '-1', 'Unknown Extra Item', '0','0');

INSERT INTO "DIM_PAYMENT_METHODS" (DIM_PAYMENT_METHODS_ID, PAYMENT_METHOD) VALUES ('-404', 'Payment not recognized');
INSERT INTO "DIM_PAYMENT_METHODS" (PAYMENT_METHOD) VALUES ('Cash');
INSERT INTO "DIM_PAYMENT_METHODS" (PAYMENT_METHOD) VALUES ('VISA');
INSERT INTO "DIM_PAYMENT_METHODS" (PAYMENT_METHOD) VALUES ('Credit Card');

INSERT INTO "DIM_CUSTOMERS" (DIM_CUSTOMERS_ID, ORIGINAL_PERS_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAMES, BIRTHDATE, EMAIL) VALUES ('-404', '-1', 'N/A', 'N/A', 'N/A', TO_DATE('1991-05-02 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'NONE@MAIL.COM');

commit;