prompt REMOVING OLD TABLES
drop table detailed_item_sales_fact;
drop table item_sales_fact;
drop table payment_fact;
drop table dim_payment_methods;
drop table dim_sessions;
drop table dim_employees_history;
drop table dim_employees;
drop table dim_customers;
drop table dim_selections;
drop table prod_menus_history;
drop table prod_categories_history;
drop table prod_items_history;
drop table prod_custom_items;
drop table prod_items;
drop table prod_categories;
drop table prod_menus;
drop table dim_extra_items;
drop table dim_time;
drop table dim_date;

purge dba_recyclebin;


prompt CREATING DIMENSIONS

create table dim_date (
	dim_date_id number generated by default on null as identity,
	year number(4) not null,
	halfyear number(1) not null,
	quarter number(1) not null,
	month number(2) not null,
	monthname varchar2(20) not null,
	day number(2) not null,
	week number(2) not null,
	weekday number(1) not null,
	weekdayname varchar2(20) not null,
	dayofyear number(3) not null,
	constraint pk_dim_date primary key (dim_date_id)
);


create table dim_time (
	dim_time_id number generated by default on null as identity,
	hour number(2) not null,
	minute number(2) not null,
	constraint pk_dim_time primary key (dim_time_id)
);


create table prod_menus (
	prod_menus_id number generated by default on null as identity,
	original_menu_id number default -1 not null,
	menu_name varchar2(50) not null,
	menu_description varchar2(1000),
	original_mt_id number default -1 not null,
	mt_name varchar2(50) not null,
	constraint pk_prod_menus primary key (prod_menus_id)
);

create table prod_categories (
	prod_cat_id number generated by default on null as identity,
	original_cat_id number default -1 not null,
	name varchar2(50) not null,
	description varchar2(1000),
	lft number default 0 not null,
	rgt number default 0 not null,
	prod_menus_id number default -1 not null,
	constraint pk_prod_categories primary key (prod_cat_id),
	constraint fk_prod_cat_prod_men foreign key (prod_menus_id) references prod_menus(prod_menus_id)
);

create table prod_items (
	prod_items_id number generated by default on null as identity,
	original_item_id number default -1 not null,
	name varchar2(50) not null,
	subtitle varchar2(200),
	description varchar2(1000),
	price numeric(10,2) not null,
	price_name varchar2(50),
	allergenes number default 0 not null,
	prod_cat_id number default -1 not null,
	prod_menus_id number default -1 not null,
	constraint pk_prod_items primary key (prod_items_id),
	constraint fk_prod_items_prod_cat foreign key (prod_cat_id) references prod_categories(prod_cat_id),
	constraint fk_prod_items_prod_menus foreign key (prod_menus_id) references prod_menus(prod_menus_id),
	constraint u_prod_items_itemid_price unique (prod_items_id, original_item_id, price)
);

create table prod_custom_items (
	prod_custom_items_id number generated by default on null as identity,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	original_item_id number default -1 not null,
	name varchar2(50) not null,
	subtitle varchar2(200),
	description varchar2(1000),
	allergenes number default 0 not null,
	prod_cat_id number default -1 not null,
	prod_menus_id number default -1 not null,
	constraint pk_prod_citems primary key (prod_custom_items_id),
	constraint fk_prod_citems_prod_cat foreign key (prod_cat_id) references prod_categories(prod_cat_id),
	constraint fk_prod_citems_prod_men foreign key (prod_menus_id) references prod_menus(prod_menus_id)
);


create table prod_menus_history (
	prod_menus_id number not null,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	menu_name varchar2(50) not null,
	menu_description varchar2(1000),
	mt_name varchar2(50) not null,
	constraint pk_prod_menus_hist primary key (prod_menus_id, from_date),
	constraint fk_pmh_prod_menus_id foreign key (prod_menus_id) references prod_menus(prod_menus_id)
);

create table prod_categories_history (
	prod_cat_id number not null,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	name varchar2(50) not null,
	description varchar2(1000),
	lft number not null,
	rgt number not null,
	prod_menus_id number not null,
	constraint pk_prod_cat_hist primary key (prod_cat_id, from_date),
	constraint fk_pci_prod_cat_id foreign key (prod_cat_id) references prod_categories(prod_cat_id)
);

create table prod_items_history (
	prod_items_id number not null,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	name varchar2(50) not null,
	subtitle varchar2(200),
	description varchar2(1000),
	price number(6,2) not null,
	price_name varchar2(50),
	allergenes number default 0 not null,
	prod_cat_id number not null,
	prod_menus_id number not null,
	constraint pk_prod_items_hist primary key (prod_items_id, from_date),
	constraint fk_pih_prod_items_id foreign key (prod_items_id) references prod_items(prod_items_id)
);

create table dim_selections (
	dim_selections_id number generated by default on null as identity,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	original_selg_id number default -1 not null,
	selg_name varchar2(50) not null,
	original_sel_id number default -1 not null,
	sel_name varchar2(50) not null,
	sel_description varchar2(1000),
	constraint pk_dim_sel primary key (dim_selections_id)
);

create table dim_employees (
	dim_employees_id number generated by default on null as identity,
	original_emp_id number default -1 not null,
	last_name varchar2(50) not null,
	first_name varchar2(50) not null,
	middle_names varchar2(200),
	gender char default 'I',
	birthdate date default to_date('01.01.1900','DD.MM.YYYY') not null,
	original_job_id number default -1 not null,
	job_title varchar2(50) not null,
	constraint pk_dim_emp primary key (dim_employees_id),
	constraint ck_dim_emp_gender check (UPPER(gender) in ('I','M','F'))
);

create table dim_employees_history (
	dim_employees_id number not null,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	last_name varchar2(50) not null,
	first_name varchar2(50) not null,
	middle_names varchar2(200),
	job_title varchar2(50),
	constraint pk_dim_emp_hist primary key (dim_employees_id, from_date),
	constraint fk_deh_dim_emp_id foreign key (dim_employees_id) references dim_employees(dim_employees_id) 
);

create table dim_sessions (
	dim_sessions_id number generated by default on null as identity,
	session_guid varchar2(36) unique not null,
	session_start timestamp default systimestamp not null,
	session_closed timestamp default to_timestamp('31.12.2999','DD.MM.YYYY') not null,
	session_status char default 'O' not null,
	constraint pk_dim_sessions primary key (dim_sessions_id),
	constraint ck_dim_sess_status check (UPPER(session_status) in ('O','P','E')) -- O pen, P aid, E xpired
);

create table dim_payment_methods (
	dim_payment_methods_id number generated by default on null as identity,
	payment_method varchar2(50) not null,
	constraint pk_dim_pay_method primary key (dim_payment_methods_id)
);

create table dim_customers (
	dim_customers_id number generated by default on null as identity,
	original_pers_id number default -1 not null,
	last_name varchar2(50) not null,
	first_name varchar2(50) not null,
	middle_names varchar2(200),
	gender char default 'I',
	birthdate date,
	email varchar2(150) not null,
	constraint pk_dim_cust primary key (dim_customers_id),
	constraint ck_dc_gender check(UPPER(gender) in ('I','M','F')),
    constraint ck_dc_email check(REGEXP_LIKE (UPPER(email), '[A-Za-z0-9._%-]+@[A-Za-z0-9._%-]+\.[A-Za-z]{2,4}'))
);

create table dim_extra_items (
	dim_extra_items_id number generated by default on null as identity,
	from_date date default sysdate not null,
	end_date date default to_date('31.12.2999','DD.MM.YYYY') not null,
	original_exitem_id number default -1 not null,
	name varchar2(50) not null,
	price number(3,2) not null,
	allergenes number default 0 not null,
	constraint pk_dim_extra_items primary key (dim_extra_items_id)
);

prompt CREATING FACT TABLES

create table item_sales_fact (
	isf_guid raw(36) default SYS_GUID() not null,
	quantity_sold number not null,
	price numeric(10,2) not null,
	dim_date_id number not null,
	dim_time_id number not null,
	prod_items_id number default -1 not null,
	dim_employees_id number default -1 not null,
	dim_sessions_id number default -1 not null,
	dim_customers_id number default -1 not null,
	load_timestamp timestamp default systimestamp not null,
	constraint pk_f_sales primary key (isf_guid, dim_date_id, dim_time_id, prod_items_id, dim_employees_id, dim_sessions_id, dim_customers_id),
	constraint fk_f_sales_dim_date foreign key (dim_date_id) references dim_date(dim_date_id),
	constraint fk_f_sales_dim_time foreign key (dim_time_id) references dim_time(dim_time_id),
	constraint fk_f_sales_prod_items foreign key (prod_items_id) references prod_items(prod_items_id),
	constraint fk_f_sales_dim_emp foreign key (dim_employees_id) references dim_employees(dim_employees_id),
	constraint fk_f_sales_dim_sess foreign key (dim_sessions_id) references dim_sessions(dim_sessions_id),
	constraint fk_f_sales_dim_cust foreign key (dim_customers_id) references dim_customers(dim_customers_id)
);

create table detailed_item_sales_fact (
	disf_guid raw(36) default SYS_GUID() not null,
	isf_guid raw(36) not null,
	dim_date_id number not null,
	dim_time_id number not null,
	prod_items_id number not null,
	dim_employees_id number not null,
	dim_sessions_id number not null,
	dim_customers_id number not null,
	prod_custom_items_id number default -1 not null,
	dim_selections_id number default -1 not null,
	dim_extra_items_id number default -1 not null,
	load_timestamp timestamp default systimestamp not null,
	constraint pk_f_di_sales primary key (disf_guid, dim_date_id, dim_time_id, prod_items_id, prod_custom_items_id, dim_selections_id, dim_employees_id, dim_sessions_id, dim_customers_id),
	constraint fk_f_di_sales_dim_date foreign key (isf_guid, dim_date_id, dim_time_id, prod_items_id, dim_employees_id, dim_sessions_id, dim_customers_id) references item_sales_fact(isf_guid, dim_date_id, dim_time_id, prod_items_id, dim_employees_id, dim_sessions_id, dim_customers_id),
	constraint fk_f_di_sales_prod_citems foreign key (prod_custom_items_id) references prod_custom_items(prod_custom_items_id),
	constraint fk_f_di_sales_dim_selections foreign key (dim_selections_id) references dim_selections(dim_selections_id),
	constraint fk_f_di_sales_dim_extra_items foreign key (dim_extra_items_id) references dim_extra_items(dim_extra_items_id)
);

create table payment_fact (
	pf_guid raw(36) default SYS_GUID() not null,
	price_paid number not null,
	discount number default 0 not null,
	bonus_points number not null,
	dim_date_id number not null,
	dim_time_id number not null,
	dim_sessions_id number default -1 not null, 
	dim_employees_id number default -1 not null,
	dim_payment_methods_id number default -1 not null,
	dim_customers_id number default -1 not null,
	load_timestamp timestamp default systimestamp not null,
	constraint pk_f_p primary key (pf_guid, dim_date_id, dim_time_id, dim_sessions_id, dim_employees_id, dim_payment_methods_id, dim_customers_id),
	constraint fk_f_p_dim_date foreign key (dim_date_id) references dim_date(dim_date_id),
	constraint fk_f_p_dim_time foreign key (dim_time_id) references dim_time(dim_time_id),
	constraint fk_f_p_dim_sessions foreign key (dim_sessions_id) references dim_sessions(dim_sessions_id),
	constraint fk_f_p_dim_employees foreign key (dim_employees_id) references dim_employees(dim_employees_id),
	constraint fk_f_p_dim_payment_methods foreign key (dim_payment_methods_id) references dim_payment_methods(dim_payment_methods_id),
	constraint fk_f_p_dim_cust foreign key (dim_customers_id) references dim_customers(dim_customers_id)
);

